name: thespot_jobfinder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^11.2.0
  google_mobile_ads: ^9.1.0
  google_sign_in: ^7.2.0
  http: ^1.6.0
  url_launcher: ^6.3.2
  video_player: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
